version: '3.8'

services:
  backend:
    build: ./backend
    container_name: storechat_backend
    restart: always
    env_file: .env
    volumes:
      - ./backend:/app
      - /app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - redis
    entrypoint: ["/app/init.sh"]

  frontend:
    build: ./frontend
    container_name: storechat_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000


  redis:
    image: redis:latest
    container_name: storechat_redis
    restart: always
    ports:
      - "6379:6379"

