# Generated by Django 4.1 on 2025-02-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
