# Generated by Django 4.1 on 2025-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
