# Generated by Django 4.1 on 2025-02-06 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chatmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='llm_response',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user_input',
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='New Session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
